name = "FaSTLMMlight"
uuid = "26e330ee-2514-4fac-b42d-929ac0d6997d"
authors = ["tmichoel <11647967+tmichoel@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
